name: "Request Grade"
description: "Request or record a grade."
title: "Request Grade: ASSIGNMENT"

body:
  - type: markdown
    attributes:
      value: |
        :warning: If you already have an issue created for this assignment, please re-open that issue rather than create a new one!

  - type: markdown
    attributes:
      value: |
        Use this issue to *manually* request a project tests grade.

  - type: input
    id: full_name
    attributes:
      label: Full Name
      description: Please enter your full name.
      placeholder: Full Name
    validations:
      required: true

  - type: input
    id: usf_email
    attributes:
      label: USF Email
      description: Please enter your USF email address.
      placeholder: username@dons.usfca.edu
    validations:
      required: true

  - type: dropdown
    id: assignment
    attributes:
      label: Please select the assignment to grade.
      multiple: false
      options:
        - ArgumentParser
        - FileStemmer
        - JsonWriter
        - FileIndex
        - FileSorter
        - FileFinder
        - LoggerSetup
        - MultiReaderLock
        - PrimeFinder
        - HtmlFetcher
        - HtmlCleaner
        - LinkFinder
        - Bundle 1 Review
        - Bundle 3 Review
        - Bundle 4 Review
        - Project v1.0 Tests
        - Project v1.1 Tests
        - Project v1.2 Review
        - Project v1.3 Review
        - Project v1.4 Design
        - Project v2.0 Tests
        - Project v2.1 Tests
        - Project v2.2 Review
        - Project v2.3 Review
        - Project v2.4 Design
        - Project v3.0 Tests
        - Project v3.1 Tests
        - Project v3.2 Review
        - Project v3.3 Review
        - Project v3.4 Design
        - Project v4.0 Tests
        - Project v4.1 Tests
        - Project v4.2 Design
        - Project v5.0 Tests
        - Project v5.1 Tests
    validations:
      required: true

  - type: input
    id: action_url
    attributes:
      label: Github Action Run
      description: Please enter the URL to the GitHub Action run that shows you are passing this assignment.
      placeholder: https://github.com/usf-cs272-spring2024/[REPO]/actions/runs/[RUNID]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        After opening this issue, reach out on Piazza to have the instructor review your request.

